### ISSUE TITLE
csv download

### ISSUE THREAD

**Issue by justinelliotmeyers** [amandasaurus/logainm-parse#2]
hello! do you know where a current csv download for the placenames data is? Cannot find anything on their site!?  Thanks

**Comment by amandasaurus** [comment]
Sorry, I'm not sure, this is a very old project. You could start looking here https://www.logainm.ie/en/inf/proj-xml and maybe mass download from the API, which I think I did once. I think Logainm have changed things since I wrote this project.

**Comment by justinelliotmeyers** [comment]
Thanks
